//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.06 at 11:07:39 AM GMT-03:00 
//


package br.gov.bnb.s095.autodeploy.xml.ns.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://autodeploy.s095.bnb.gov.br/xml/ns/v1}alias"/>
 *         &lt;element ref="{http://autodeploy.s095.bnb.gov.br/xml/ns/v1}estrategia-autenticacao"/>
 *         &lt;element ref="{http://autodeploy.s095.bnb.gov.br/xml/ns/v1}nome-classe-modulo"/>
 *         &lt;element ref="{http://autodeploy.s095.bnb.gov.br/xml/ns/v1}propriedades-personalizadas"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "alias",
    "estrategiaAutenticacao",
    "nomeClasseModulo",
    "propriedadesPersonalizadas"
})
@XmlRootElement(name = "seguranca-login-aplicativo")
public class SegurancaLoginAplicativo {

    @XmlElement(required = true)
    protected Alias alias;
    @XmlElement(name = "estrategia-autenticacao", required = true)
    protected EstrategiaAutenticacao estrategiaAutenticacao;
    @XmlElement(name = "nome-classe-modulo", required = true)
    protected NomeClasseModulo nomeClasseModulo;
    @XmlElement(name = "propriedades-personalizadas", required = true)
    protected PropriedadesPersonalizadas propriedadesPersonalizadas;

    /**
     * Gets the value of the alias property.
     * 
     * @return
     *     possible object is
     *     {@link Alias }
     *     
     */
    public Alias getAlias() {
        return alias;
    }

    /**
     * Sets the value of the alias property.
     * 
     * @param value
     *     allowed object is
     *     {@link Alias }
     *     
     */
    public void setAlias(Alias value) {
        this.alias = value;
    }

    /**
     * Gets the value of the estrategiaAutenticacao property.
     * 
     * @return
     *     possible object is
     *     {@link EstrategiaAutenticacao }
     *     
     */
    public EstrategiaAutenticacao getEstrategiaAutenticacao() {
        return estrategiaAutenticacao;
    }

    /**
     * Sets the value of the estrategiaAutenticacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link EstrategiaAutenticacao }
     *     
     */
    public void setEstrategiaAutenticacao(EstrategiaAutenticacao value) {
        this.estrategiaAutenticacao = value;
    }

    /**
     * Gets the value of the nomeClasseModulo property.
     * 
     * @return
     *     possible object is
     *     {@link NomeClasseModulo }
     *     
     */
    public NomeClasseModulo getNomeClasseModulo() {
        return nomeClasseModulo;
    }

    /**
     * Sets the value of the nomeClasseModulo property.
     * 
     * @param value
     *     allowed object is
     *     {@link NomeClasseModulo }
     *     
     */
    public void setNomeClasseModulo(NomeClasseModulo value) {
        this.nomeClasseModulo = value;
    }

    /**
     * Gets the value of the propriedadesPersonalizadas property.
     * 
     * @return
     *     possible object is
     *     {@link PropriedadesPersonalizadas }
     *     
     */
    public PropriedadesPersonalizadas getPropriedadesPersonalizadas() {
        return propriedadesPersonalizadas;
    }

    /**
     * Sets the value of the propriedadesPersonalizadas property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropriedadesPersonalizadas }
     *     
     */
    public void setPropriedadesPersonalizadas(PropriedadesPersonalizadas value) {
        this.propriedadesPersonalizadas = value;
    }

}
