//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.01 at 11:36:34 AM GMT-03:00 
//


package oasis.names.tc.opendocument.xmlns.office._1;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the oasis.names.tc.opendocument.xmlns.office._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: oasis.names.tc.opendocument.xmlns.office._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Scripts }
     * 
     */
    public Scripts createScripts() {
        return new Scripts();
    }

    /**
     * Create an instance of {@link AutomaticStyles }
     * 
     */
    public AutomaticStyles createAutomaticStyles() {
        return new AutomaticStyles();
    }

    /**
     * Create an instance of {@link FontFaceDecls }
     * 
     */
    public FontFaceDecls createFontFaceDecls() {
        return new FontFaceDecls();
    }

    /**
     * Create an instance of {@link Text }
     * 
     */
    public Text createText() {
        return new Text();
    }

    /**
     * Create an instance of {@link DocumentContent }
     * 
     */
    public DocumentContent createDocumentContent() {
        return new DocumentContent();
    }

    /**
     * Create an instance of {@link Body }
     * 
     */
    public Body createBody() {
        return new Body();
    }

}
