//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.01 at 10:38:59 AM GMT-03:00 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:oasis:names:tc:opendocument:xmlns:office:1.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package oasis.names.tc.opendocument.xmlns.office._1;
