//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.06 at 10:04:39 AM GMT-03:00 
//


package br.gov.bnb.s095.autodeploy.xml.ns.v1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.gov.bnb.s095.autodeploy.xml.ns.v1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Item_QNAME = new QName("http://autodeploy.s095.bnb.gov.br/xml/ns/v1", "item");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.gov.bnb.s095.autodeploy.xml.ns.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Aplicacao }
     * 
     */
    public Aplicacao createAplicacao() {
        return new Aplicacao();
    }

    /**
     * Create an instance of {@link UtilizarCmp }
     * 
     */
    public UtilizarCmp createUtilizarCmp() {
        return new UtilizarCmp();
    }

    /**
     * Create an instance of {@link NomeModuloWEB }
     * 
     */
    public NomeModuloWEB createNomeModuloWEB() {
        return new NomeModuloWEB();
    }

    /**
     * Create an instance of {@link ProcessarConfiguracaoIncorporada }
     * 
     */
    public ProcessarConfiguracaoIncorporada createProcessarConfiguracaoIncorporada() {
        return new ProcessarConfiguracaoIncorporada();
    }

    /**
     * Create an instance of {@link NomeServidor }
     * 
     */
    public NomeServidor createNomeServidor() {
        return new NomeServidor();
    }

    /**
     * Create an instance of {@link ImplementarBeansCorporativos }
     * 
     */
    public ImplementarBeansCorporativos createImplementarBeansCorporativos() {
        return new ImplementarBeansCorporativos();
    }

    /**
     * Create an instance of {@link ListaDeMateriais }
     * 
     */
    public ListaDeMateriais createListaDeMateriais() {
        return new ListaDeMateriais();
    }

    /**
     * Create an instance of {@link PortaServidor }
     * 
     */
    public PortaServidor createPortaServidor() {
        return new PortaServidor();
    }

    /**
     * Create an instance of {@link AliasAutenticacao }
     * 
     */
    public AliasAutenticacao createAliasAutenticacao() {
        return new AliasAutenticacao();
    }

    /**
     * Create an instance of {@link CelulaNoServidorDestino }
     * 
     */
    public CelulaNoServidorDestino createCelulaNoServidorDestino() {
        return new CelulaNoServidorDestino();
    }

    /**
     * Create an instance of {@link DistribuirAplicativo }
     * 
     */
    public DistribuirAplicativo createDistribuirAplicativo() {
        return new DistribuirAplicativo();
    }

    /**
     * Create an instance of {@link LocalizacaoPacoteAplicativo }
     * 
     */
    public LocalizacaoPacoteAplicativo createLocalizacaoPacoteAplicativo() {
        return new LocalizacaoPacoteAplicativo();
    }

    /**
     * Create an instance of {@link EscopoProvedor }
     * 
     */
    public EscopoProvedor createEscopoProvedor() {
        return new EscopoProvedor();
    }

    /**
     * Create an instance of {@link Alias }
     * 
     */
    public Alias createAlias() {
        return new Alias();
    }

    /**
     * Create an instance of {@link MapeamentoModulosServidores }
     * 
     */
    public MapeamentoModulosServidores createMapeamentoModulosServidores() {
        return new MapeamentoModulosServidores();
    }

    /**
     * Create an instance of {@link BibliotecasCompartilhadas }
     * 
     */
    public BibliotecasCompartilhadas createBibliotecasCompartilhadas() {
        return new BibliotecasCompartilhadas();
    }

    /**
     * Create an instance of {@link Descricao }
     * 
     */
    public Descricao createDescricao() {
        return new Descricao();
    }

    /**
     * Create an instance of {@link NomeRaizContexto }
     * 
     */
    public NomeRaizContexto createNomeRaizContexto() {
        return new NomeRaizContexto();
    }

    /**
     * Create an instance of {@link Senha }
     * 
     */
    public Senha createSenha() {
        return new Senha();
    }

    /**
     * Create an instance of {@link NomeOrigem }
     * 
     */
    public NomeOrigem createNomeOrigem() {
        return new NomeOrigem();
    }

    /**
     * Create an instance of {@link PreCompilarArquivosJSP }
     * 
     */
    public PreCompilarArquivosJSP createPreCompilarArquivosJSP() {
        return new PreCompilarArquivosJSP();
    }

    /**
     * Create an instance of {@link EstaEmCluster }
     * 
     */
    public EstaEmCluster createEstaEmCluster() {
        return new EstaEmCluster();
    }

    /**
     * Create an instance of {@link NomeProvedor }
     * 
     */
    public NomeProvedor createNomeProvedor() {
        return new NomeProvedor();
    }

    /**
     * Create an instance of {@link NomeBancodedados }
     * 
     */
    public NomeBancodedados createNomeBancodedados() {
        return new NomeBancodedados();
    }

    /**
     * Create an instance of {@link CriarMBeansParaRecursos }
     * 
     */
    public CriarMBeansParaRecursos createCriarMBeansParaRecursos() {
        return new CriarMBeansParaRecursos();
    }

    /**
     * Create an instance of {@link RecursoDatasource }
     * 
     */
    public RecursoDatasource createRecursoDatasource() {
        return new RecursoDatasource();
    }

    /**
     * Create an instance of {@link ValidarEntrada }
     * 
     */
    public ValidarEntrada createValidarEntrada() {
        return new ValidarEntrada();
    }

    /**
     * Create an instance of {@link SegurancaJ2C }
     * 
     */
    public SegurancaJ2C createSegurancaJ2C() {
        return new SegurancaJ2C();
    }

    /**
     * Create an instance of {@link PermissoesArquivo }
     * 
     */
    public PermissoesArquivo createPermissoesArquivo() {
        return new PermissoesArquivo();
    }

    /**
     * Create an instance of {@link NomeClasseHelper }
     * 
     */
    public NomeClasseHelper createNomeClasseHelper() {
        return new NomeClasseHelper();
    }

    /**
     * Create an instance of {@link NomeJndi }
     * 
     */
    public NomeJndi createNomeJndi() {
        return new NomeJndi();
    }

    /**
     * Create an instance of {@link NomeAplicativo }
     * 
     */
    public NomeAplicativo createNomeAplicativo() {
        return new NomeAplicativo();
    }

    /**
     * Create an instance of {@link Usuario }
     * 
     */
    public Usuario createUsuario() {
        return new Usuario();
    }

    /**
     * Create an instance of {@link NomeModulosEJB }
     * 
     */
    public NomeModulosEJB createNomeModulosEJB() {
        return new NomeModulosEJB();
    }

    /**
     * Create an instance of {@link DiretorioInstalacaoAplicativo }
     * 
     */
    public DiretorioInstalacaoAplicativo createDiretorioInstalacaoAplicativo() {
        return new DiretorioInstalacaoAplicativo();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autodeploy.s095.bnb.gov.br/xml/ns/v1", name = "item")
    public JAXBElement<String> createItem(String value) {
        return new JAXBElement<String>(_Item_QNAME, String.class, null, value);
    }

}
