//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package br.gov.bnb.autodeploy.integra.servico;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "ExecutaService", targetNamespace = "http://servico.autodeploy.support.bnb.gov.br/", wsdlLocation = "META-INF/wsdl/ExecutaService.wsdl")
public class ExecutaService
    extends Service
{

    private final static URL EXECUTASERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.gov.bnb.autodeploy.integra.servico.ExecutaService.class.getName());

    static {
        URL url = null;
        try {
            url = br.gov.bnb.autodeploy.integra.servico.ExecutaService.class.getResource("/META-INF/wsdl/ExecutaService.wsdl");
            if (url == null) throw new MalformedURLException("/META-INF/wsdl/ExecutaService.wsdl does not exist in the module.");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'META-INF/wsdl/ExecutaService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        EXECUTASERVICE_WSDL_LOCATION = url;
    }

    public ExecutaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExecutaService() {
        super(EXECUTASERVICE_WSDL_LOCATION, new QName("http://servico.autodeploy.support.bnb.gov.br/", "ExecutaService"));
    }

    /**
     * 
     * @return
     *     returns Executa
     */
    @WebEndpoint(name = "ExecutaPort")
    public Executa getExecutaPort() {
        return super.getPort(new QName("http://servico.autodeploy.support.bnb.gov.br/", "ExecutaPort"), Executa.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Executa
     */
    @WebEndpoint(name = "ExecutaPort")
    public Executa getExecutaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servico.autodeploy.support.bnb.gov.br/", "ExecutaPort"), Executa.class, features);
    }

}
