//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package br.gov.bnb.autodeploy.integra.servico;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "Executa", targetNamespace = "http://servico.autodeploy.support.bnb.gov.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Executa {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "executar", targetNamespace = "http://servico.autodeploy.support.bnb.gov.br/", className = "br.gov.bnb.autodeploy.integra.servico.Executar")
    @ResponseWrapper(localName = "executarResponse", targetNamespace = "http://servico.autodeploy.support.bnb.gov.br/", className = "br.gov.bnb.autodeploy.integra.servico.ExecutarResponse")
    public String executar();

}
