//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package br.gov.bnb.autodeploy.integra.servico;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.gov.bnb.autodeploy.integra.servico package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Executar_QNAME = new QName("http://servico.autodeploy.support.bnb.gov.br/", "executar");
    private final static QName _ExecutarResponse_QNAME = new QName("http://servico.autodeploy.support.bnb.gov.br/", "executarResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.gov.bnb.autodeploy.integra.servico
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Executar }
     * 
     */
    public Executar createExecutar() {
        return new Executar();
    }

    /**
     * Create an instance of {@link ExecutarResponse }
     * 
     */
    public ExecutarResponse createExecutarResponse() {
        return new ExecutarResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Executar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://servico.autodeploy.support.bnb.gov.br/", name = "executar")
    public JAXBElement<Executar> createExecutar(Executar value) {
        return new JAXBElement<Executar>(_Executar_QNAME, Executar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExecutarResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://servico.autodeploy.support.bnb.gov.br/", name = "executarResponse")
    public JAXBElement<ExecutarResponse> createExecutarResponse(ExecutarResponse value) {
        return new JAXBElement<ExecutarResponse>(_ExecutarResponse_QNAME, ExecutarResponse.class, null, value);
    }

}
