//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://servico.autodeploy.support.bnb.gov.br/")
package br.gov.bnb.autodeploy.integra.servico;
