//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.03 at 01:08:15 PM GMT-03:00 
//


package br.gov.bnb.s095.autodeploy.xml.ns.v1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.gov.bnb.s095.autodeploy.xml.ns.v1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ImplementarBeansCorporativos_QNAME = new QName("http://autodeploy.s095.bnb.gov.br/xml/ns/v1", "implementar-beans-corporativos");
    private final static QName _ValidarEntrada_QNAME = new QName("http://autodeploy.s095.bnb.gov.br/xml/ns/v1", "validar-entrada");
    private final static QName _NomeModuloWEB_QNAME = new QName("http://autodeploy.s095.bnb.gov.br/xml/ns/v1", "nome-modulo-wEB");
    private final static QName _DiretorioInstalacaoAplicativo_QNAME = new QName("http://autodeploy.s095.bnb.gov.br/xml/ns/v1", "diretorio-instalacao-aplicativo");
    private final static QName _NomeModulosEJB_QNAME = new QName("http://autodeploy.s095.bnb.gov.br/xml/ns/v1", "nome-modulos-eJB");
    private final static QName _ProcessarConfiguracaoIncorporada_QNAME = new QName("http://autodeploy.s095.bnb.gov.br/xml/ns/v1", "processar-configuracao-incorporada");
    private final static QName _PermissoesArquivo_QNAME = new QName("http://autodeploy.s095.bnb.gov.br/xml/ns/v1", "permissoes-arquivo");
    private final static QName _EstaEmCluster_QNAME = new QName("http://autodeploy.s095.bnb.gov.br/xml/ns/v1", "esta-em-cluster");
    private final static QName _BibliotecasCompartilhadas_QNAME = new QName("http://autodeploy.s095.bnb.gov.br/xml/ns/v1", "bibliotecas-compartilhadas");
    private final static QName _MapeamentoModulosServidores_QNAME = new QName("http://autodeploy.s095.bnb.gov.br/xml/ns/v1", "mapeamento-modulos-servidores");
    private final static QName _PreCompilarArquivosJSP_QNAME = new QName("http://autodeploy.s095.bnb.gov.br/xml/ns/v1", "pre-compilar-Arquivos-jSP");
    private final static QName _CriarMBeansParaRecursos_QNAME = new QName("http://autodeploy.s095.bnb.gov.br/xml/ns/v1", "criar-mBeans-para-recursos");
    private final static QName _DistribuirAplicativo_QNAME = new QName("http://autodeploy.s095.bnb.gov.br/xml/ns/v1", "distribuir-aplicativo");
    private final static QName _NomeAplicativo_QNAME = new QName("http://autodeploy.s095.bnb.gov.br/xml/ns/v1", "nome-aplicativo");
    private final static QName _CelulaNoServidorDestino_QNAME = new QName("http://autodeploy.s095.bnb.gov.br/xml/ns/v1", "celula-no-servidor-destino");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.gov.bnb.s095.autodeploy.xml.ns.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ListaDeMateriais }
     * 
     */
    public ListaDeMateriais createListaDeMateriais() {
        return new ListaDeMateriais();
    }

    /**
     * Create an instance of {@link LocalizacaoPacoteAplicativo }
     * 
     */
    public LocalizacaoPacoteAplicativo createLocalizacaoPacoteAplicativo() {
        return new LocalizacaoPacoteAplicativo();
    }

    /**
     * Create an instance of {@link NomeRaizContexto }
     * 
     */
    public NomeRaizContexto createNomeRaizContexto() {
        return new NomeRaizContexto();
    }

    /**
     * Create an instance of {@link Aplicacao }
     * 
     */
    public Aplicacao createAplicacao() {
        return new Aplicacao();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autodeploy.s095.bnb.gov.br/xml/ns/v1", name = "implementar-beans-corporativos")
    public JAXBElement<String> createImplementarBeansCorporativos(String value) {
        return new JAXBElement<String>(_ImplementarBeansCorporativos_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autodeploy.s095.bnb.gov.br/xml/ns/v1", name = "validar-entrada")
    public JAXBElement<String> createValidarEntrada(String value) {
        return new JAXBElement<String>(_ValidarEntrada_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autodeploy.s095.bnb.gov.br/xml/ns/v1", name = "nome-modulo-wEB")
    public JAXBElement<String> createNomeModuloWEB(String value) {
        return new JAXBElement<String>(_NomeModuloWEB_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autodeploy.s095.bnb.gov.br/xml/ns/v1", name = "diretorio-instalacao-aplicativo")
    public JAXBElement<String> createDiretorioInstalacaoAplicativo(String value) {
        return new JAXBElement<String>(_DiretorioInstalacaoAplicativo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autodeploy.s095.bnb.gov.br/xml/ns/v1", name = "nome-modulos-eJB")
    public JAXBElement<String> createNomeModulosEJB(String value) {
        return new JAXBElement<String>(_NomeModulosEJB_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autodeploy.s095.bnb.gov.br/xml/ns/v1", name = "processar-configuracao-incorporada")
    public JAXBElement<String> createProcessarConfiguracaoIncorporada(String value) {
        return new JAXBElement<String>(_ProcessarConfiguracaoIncorporada_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autodeploy.s095.bnb.gov.br/xml/ns/v1", name = "permissoes-arquivo")
    public JAXBElement<String> createPermissoesArquivo(String value) {
        return new JAXBElement<String>(_PermissoesArquivo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autodeploy.s095.bnb.gov.br/xml/ns/v1", name = "esta-em-cluster")
    public JAXBElement<String> createEstaEmCluster(String value) {
        return new JAXBElement<String>(_EstaEmCluster_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autodeploy.s095.bnb.gov.br/xml/ns/v1", name = "bibliotecas-compartilhadas")
    public JAXBElement<String> createBibliotecasCompartilhadas(String value) {
        return new JAXBElement<String>(_BibliotecasCompartilhadas_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autodeploy.s095.bnb.gov.br/xml/ns/v1", name = "mapeamento-modulos-servidores")
    public JAXBElement<String> createMapeamentoModulosServidores(String value) {
        return new JAXBElement<String>(_MapeamentoModulosServidores_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autodeploy.s095.bnb.gov.br/xml/ns/v1", name = "pre-compilar-Arquivos-jSP")
    public JAXBElement<String> createPreCompilarArquivosJSP(String value) {
        return new JAXBElement<String>(_PreCompilarArquivosJSP_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autodeploy.s095.bnb.gov.br/xml/ns/v1", name = "criar-mBeans-para-recursos")
    public JAXBElement<String> createCriarMBeansParaRecursos(String value) {
        return new JAXBElement<String>(_CriarMBeansParaRecursos_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autodeploy.s095.bnb.gov.br/xml/ns/v1", name = "distribuir-aplicativo")
    public JAXBElement<String> createDistribuirAplicativo(String value) {
        return new JAXBElement<String>(_DistribuirAplicativo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autodeploy.s095.bnb.gov.br/xml/ns/v1", name = "nome-aplicativo")
    public JAXBElement<String> createNomeAplicativo(String value) {
        return new JAXBElement<String>(_NomeAplicativo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autodeploy.s095.bnb.gov.br/xml/ns/v1", name = "celula-no-servidor-destino")
    public JAXBElement<String> createCelulaNoServidorDestino(String value) {
        return new JAXBElement<String>(_CelulaNoServidorDestino_QNAME, String.class, null, value);
    }

}
