//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.03 at 01:08:15 PM GMT-03:00 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://autodeploy.s095.bnb.gov.br/xml/ns/v1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package br.gov.bnb.s095.autodeploy.xml.ns.v1;
