//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package br.gov.bnb.support.autodeploy.servico.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "executar", namespace = "http://servico.autodeploy.support.bnb.gov.br/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "executar", namespace = "http://servico.autodeploy.support.bnb.gov.br/")
public class Executar {


}
